// One-shot deletion of cached bridge icon PNGs ([Icons] DeleteIconCache + optional name filter). Runs after LoadAll (needs RegisteredAssetIds); removed icons fall back to the normal chain and re-capture on hover.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace MoreHeadBridge;

internal static class IconCacheCleaner
{
    internal static void Run()
    {
        if (!Plugin.DeleteIconCache.Value) return;

        try
        {
            string dir = IconCapture.CacheDir;
            if (!Directory.Exists(dir))
            {
                BceConsole.LogInfo("DeleteIconCache: no cache directory, nothing to do");
                ResetFlag();
                return;
            }

            string filterRaw = Plugin.DeleteIconsMatching.Value ?? "";
            string[] filters = filterRaw
                .Split(',')
                .Select(s => s.Trim().ToLowerInvariant())
                .Where(s => s.Length > 0)
                .ToArray();

            var bridgeNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (string id in HhhCosmeticLoader.RegisteredAssetIds)
            {
                int colon = id.IndexOf(':');
                if (colon < 0 || colon + 1 >= id.Length) continue;
                bridgeNames.Add(id[(colon + 1)..]);
            }

            int deleted = 0;
            int kept = 0;

            // Mini-Semibot's cached PNG (procedural / captured avatar photo) must survive Clear Icons —
            // it has no mesh to re-render, so once deleted it could not be regenerated by the batch.
            string semibotIconName = MiniSemibotCosmetic.InternalName.ToLowerInvariant();

            foreach (string file in Directory.GetFiles(dir, "*.png"))
            {
                string name = Path.GetFileNameWithoutExtension(file).ToLowerInvariant();

                if (name == semibotIconName) { kept++; continue; }

                // Only touch files whose name matches a registered bridge cosmetic.
                bool isBridge = bridgeNames.Contains(name);

                if (!isBridge) { kept++; continue; }

                if (filters.Length > 0 && !filters.Any(f => name.Contains(f)))
                {
                    kept++;
                    continue;
                }

                try { File.Delete(file); deleted++; }
                catch (Exception ex)
                {
                    BceConsole.LogWarning($"Failed to delete '{file}': {ex.Message}");
                }
            }

            BceConsole.LogInfo(
                $"DeleteIconCache: removed {deleted} bridge icon(s), kept {kept}. " +
                $"Filter: {(filters.Length == 0 ? "(all bridge icons)" : string.Join(",", filters))}");

            // Sync the in-memory cache with the on-disk deletions — else HasCache() stays true and the old sprite stays loaded until a game restart.
            if (deleted > 0)
                IconCapture.InvalidateAll();
        }
        catch (Exception ex)
        {
            BceConsole.LogError($"DeleteIconCache failed: {ex.Message}");
        }
        finally
        {
            ResetFlag();
        }
    }

    private static void ResetFlag()
    {
        Plugin.DeleteIconCache.Value = false;
        Plugin.Instance.Config.Save();
    }
}
